#pro环境配置文件
server:
  port: 8082

# spring dataSource 配置

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wistronits@123
    # 这里的新版本还需指定时区 UTC 格林威治时间
    url: jdbc:mysql://10.5.2.16:3306/taiping?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
     #      初始化大小
    initialSize: 5
    #      最小连接数
    minIdle: 5
    #      最大连接数
    maxActive: 20
    #      获取连接等待超时时间
    maxWait: 60000
    #      间隔多久检测一次 检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    #      一个连接最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #      配置监控统计拦截的filter , 去掉后监控sql无法统计wall用于防火墙 这里log4j 在spring boot 2.x 上不适用
    filters: stat
    logSlowSql: true
  mail:
    host: tpma2001.wistronits.com
    username: yujieli@wistronits.com
    password: Heimou123
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#mybaits-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.taiping.entity
  configuration:
   map-underscore-to-camel-case: true
# ftp 配置
ftp:
 host: 10.5.2.16
 userName: anonymous
# 匿名登录不需要密码  后续不是匿名的 可以设定用户名和密码
 password:
 port: 21
 # ftp 匿名主目录
 homePath: /pub/
 #运维管理活动附件目录
 managePath: /pub/manage/
 #风险控制附件目录
 riskPath: /pub/risk/
 #预算与采购附件目录
 purchasePath: /pub/purchase/
 #维护保养计划附件目录
 maintenancePlanPath: /pub/maintenanceplan/
 #资产基本信息附件目录
 assetInfoPath: /pub/assertInfo